### ISSUE TITLE
Can't find Python executable "python"

### ISSUE THREAD

**Issue by SemenMartynov** [lezhenin/HttpXmlToJsonConverter#1]
```
sam@spb$ npm run docker:build

> httpxmltojson@0.0.0 docker:build /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
> docker build -t ${npm_package_name} .

Sending build context to Docker daemon 182.3 kB
Step 1/5 : FROM node:8-alpine
8-alpine: Pulling from library/node
4fe2ade4980c: Pull complete 
0ade4f5bae45: Pull complete 
fd1dceaf77f3: Pull complete 
Digest: sha256:fa979a27cee3c8664a689e27e778b766af72da52920454160421854027374f09
Status: Downloaded newer image for node:8-alpine
 ---> dc30b65a4cfe
Step 2/5 : WORKDIR /converter
 ---> 0904bdf222ee
Removing intermediate container f73bc26ccd42
Step 3/5 : ADD . /converter
 ---> 3d8cc9285a20
Removing intermediate container bd90ca794cac
Step 4/5 : RUN npm install
 ---> Running in ceb24ea527b6

> node-expat@2.3.17 install /converter/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-140-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /converter/node_modules/node-expat
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-15T16_08_51_439Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

npm ERR! Linux 4.4.0-140-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docker:build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the httpxmltojson@0.0.0 docker:build script 'docker build -t ${npm_package_name} .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the httpxmltojson package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker build -t ${npm_package_name} .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs httpxmltojson
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls httpxmltojson
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter/npm-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'docker:build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predocker:build', 'docker:build', 'postdocker:build' ]
5 info lifecycle httpxmltojson@0.0.0~predocker:build: httpxmltojson@0.0.0
6 silly lifecycle httpxmltojson@0.0.0~predocker:build: no script for predocker:build, continuing
7 info lifecycle httpxmltojson@0.0.0~docker:build: httpxmltojson@0.0.0
8 verbose lifecycle httpxmltojson@0.0.0~docker:build: unsafe-perm in lifecycle true
9 verbose lifecycle httpxmltojson@0.0.0~docker:build: PATH: /usr/share/npm/bin/node-gyp-bin:/media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter/node_modules/.bin:/home/sam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle httpxmltojson@0.0.0~docker:build: CWD: /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
11 silly lifecycle httpxmltojson@0.0.0~docker:build: Args: [ '-c', 'docker build -t ${npm_package_name} .' ]
12 silly lifecycle httpxmltojson@0.0.0~docker:build: Returned: code: 1  signal: null
13 info lifecycle httpxmltojson@0.0.0~docker:build: Failed to exec docker:build script
14 verbose stack Error: httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid httpxmltojson@0.0.0
16 verbose cwd /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
17 error Linux 4.4.0-140-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docker:build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
22 error Exit status 1
23 error Failed at the httpxmltojson@0.0.0 docker:build script 'docker build -t ${npm_package_name} .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the httpxmltojson package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     docker build -t ${npm_package_name} .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs httpxmltojson
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls httpxmltojson
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```
sam@spb$ npm -v
3.5.2

sam@spb$ python -V
Python 2.7.12

sam@spb$ python3 -V
Python 3.5.2

```

**Comment by SemenMartynov** [comment]
```
sam@spb$ python=`which python3` npm run docker:build

> httpxmltojson@0.0.0 docker:build /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
> docker build -t ${npm_package_name} .

Sending build context to Docker daemon 178.7 kB
Step 1/5 : FROM node:8-alpine
8-alpine: Pulling from library/node
Digest: sha256:fa979a27cee3c8664a689e27e778b766af72da52920454160421854027374f09
Status: Downloaded newer image for node:8-alpine
 ---> dc30b65a4cfe
Step 2/5 : WORKDIR /converter
 ---> Using cache
 ---> 0904bdf222ee
Step 3/5 : ADD . /converter
 ---> Using cache
 ---> 7f1505959a05
Step 4/5 : RUN npm install
 ---> Running in 4bdcb681448d

> node-expat@2.3.17 install /converter/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-140-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /converter/node_modules/node-expat
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-15T16_21_02_032Z-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 1

npm ERR! Linux 4.4.0-140-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docker:build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the httpxmltojson@0.0.0 docker:build script 'docker build -t ${npm_package_name} .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the httpxmltojson package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker build -t ${npm_package_name} .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs httpxmltojson
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls httpxmltojson
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter/npm-debug.log
```
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'docker:build' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'predocker:build', 'docker:build', 'postdocker:build' ]
5 info lifecycle httpxmltojson@0.0.0~predocker:build: httpxmltojson@0.0.0
6 silly lifecycle httpxmltojson@0.0.0~predocker:build: no script for predocker:build, continuing
7 info lifecycle httpxmltojson@0.0.0~docker:build: httpxmltojson@0.0.0
8 verbose lifecycle httpxmltojson@0.0.0~docker:build: unsafe-perm in lifecycle true
9 verbose lifecycle httpxmltojson@0.0.0~docker:build: PATH: /usr/share/npm/bin/node-gyp-bin:/media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter/node_modules/.bin:/home/sam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle httpxmltojson@0.0.0~docker:build: CWD: /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
11 silly lifecycle httpxmltojson@0.0.0~docker:build: Args: [ '-c', 'docker build -t ${npm_package_name} .' ]
12 silly lifecycle httpxmltojson@0.0.0~docker:build: Returned: code: 1  signal: null
13 info lifecycle httpxmltojson@0.0.0~docker:build: Failed to exec docker:build script
14 verbose stack Error: httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid httpxmltojson@0.0.0
16 verbose cwd /media/basket/home/Documents/SPbPU/SE seminars/students/HttpXmlToJsonConverter
17 error Linux 4.4.0-140-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "docker:build"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error httpxmltojson@0.0.0 docker:build: `docker build -t ${npm_package_name} .`
22 error Exit status 1
23 error Failed at the httpxmltojson@0.0.0 docker:build script 'docker build -t ${npm_package_name} .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the httpxmltojson package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     docker build -t ${npm_package_name} .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs httpxmltojson
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls httpxmltojson
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by lezhenin** [comment]
Fixed. Base docker image with node js was changed. It has python now.

Docker daemon has been adding cashed modules into image. File .dockerignore was created to prevent that.
